<?php

namespace App\Http\Resources;

use App\Http\Middleware\RequestIdMiddleware;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Collection;

class ApiResponseResource extends JsonResource
{
    public function __construct(
        private readonly bool $success,
        private readonly string $code,
        private readonly ?string $message,
        private readonly mixed $data,
    ) {
        parent::__construct(null);
    }

    /**
     * Create a success response envelope.
     */
    public static function success(string $code, ?string $message, mixed $data): self
    {
        return new self(true, $code, $message, $data);
    }

    /**
     * Create an error response envelope.
     */
    public static function error(string $code, ?string $message, mixed $data): self
    {
        return new self(false, $code, $message, $data);
    }

    public function toArray(Request $request): array
    {
        // API contract: data MUST be an object (never null).
        $data = $this->data;

        // If controller passes a JsonResource instance, resolve it into plain data.
        // JsonResource should not be nested as an object in a custom envelope.
        if ($data instanceof JsonResource) {
            $data = $data->resolve($request);
        }

        // Normalize common data containers.
        if ($data instanceof Collection) {
            $data = $data->toArray();
        }

        if ($data === null) {
            $data = (object) [];
        }

        // Request id is generated by RequestIdMiddleware and returned in response headers.
        $requestId = $request->attributes->get(RequestIdMiddleware::ATTRIBUTE_NAME);
        if (!is_string($requestId) || trim($requestId) === '') {
            $requestId = $request->headers->get(RequestIdMiddleware::HEADER_NAME);
        }

        return [
            'success' => $this->success,
            'code' => $this->code,
            'message' => $this->message,
            'data' => $data,
            'meta' => [
                'request_id' => is_string($requestId) ? $requestId : null,
                'timestamp' => now()->toISOString(),
            ],
        ];
    }
}
